export default ({
    LOGIN: "LOGIN",
    USER: "USER",
    START_SPYLOG: "START_SPYLOG",
    POPULIZE_SPYLOG: "POPULIZE_SPYLOG",
    STOP_SPYLOG: "STOP_SPYLOG",
    SELECT_DIRS: "SELECT_DIRS",
    GET_FOLDERS: "GET_FOLDERS",
    SERVER_ERORRS: "SERVER_ERORRS",
    ERROR_MESSAGES: "ERROR_MESSAGES"
})